---
- name: Test connection to servers
  hosts: master
  become: yes

  vars:
    message1: Hello
    message2: World

  tasks:

#    - name: Debug
#      debug:
#        var: message1
#
#    - name: Debug
#      debug:
#        var: message2
#
#    - name: Debug
#      debug:
#        msg: "Message: {{ message1}} {{ message2 }}"
#
#    - set_fact: full_message="{{ message1 }} {{ message2 }}"
#
#    - debug:
#        var: full_message

    - shell: uptime
      register: results

    - debug:
        var: results