---
- name: Install Apache
  hosts: master
  become: yes

  vars:
    source_file: ./website/index.html
    destin_file: /var/www/html

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Copy
      copy:
        src: "{{ source_file }}"
        dest: "{{ destin_file }}"
        mode: 0555
      notify: Restart Apache

    - name: Enable apache during restart
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
  - name: Restart Apache
    service:
      name: apache2
      state: restarted